version: "3.7"

services:
  app:
    image: node:12-alpine
    command: sh -c "npm start"
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: newhope
      PMA_HOST: mysql

  mysql:
    image: mysql:5.7
    volumes:
      - parta:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: newhope

volumes:
  parta: